# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qgis_plugin
                                 A QGIS plugin
 A plugin to sync between cartodroid and QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-10
        copyright            : (C) 2025 by ITACYL
        email                : palferfr@itacyl.es
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load qgis_plugin class from file qgis_plugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .local_sync_plugin import LocalSyncPlugin
    return LocalSyncPlugin(iface)